# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aae0839f864ea55af78aca6d61680b5b6e92ab7fbffe2ef3875d40cf2c2d4d4313e26e50bb38e7af75549fe8da70ef7a277844ab566ff197de4e72e90098d86d

test:
  secret_key_base: 32140b332ab9e8284d27670d97bf59c9342241e0f2622a7797af5a10676ed243e2350e69943422547b8c760c7ab28ccd969463a62982a6dbba23345a3e4b49f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
